[project]
name = "hessian-approximation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.9.*"
dependencies = [
    "torch==2.1.0",
    "torchvision==0.16.0",
    "transformers==4.48.0",
    "wandb==0.19.2",
    "datasets==2.18.0",
    "numpy==1.26.4",
    "scikit-learn==1.4.2",
    "accelerate==0.32.1",
    "pyyaml",
    "tqdm",
    "matplotlib",
    "pandas",
    "easydict",
]
